Reservation table:-
Create table reservation(
ID INT NOT NULL AUTO_INCREMENT,
CHECKED_IN TINYINT(1), 
NUMBER_OF_BAGS INT,
PASSENGER_ID INT,
FLIGHT_ID INT,
CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID),
FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGER(ID) ON DELETE CASCADE,
FOREIGN KEY(FLIGHT_ID) REFERENCES FLIGHT(ID)
)

PASSENGER:- 
CREATE TABLE PASSENGER(
ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(256),
LAST_NAME VARCHAR(256),
MIDDLE_NAME VARCHAR(256),
EMAIL VARCHAR(50),
PHONE VARCHAR(10),
PRIMARY KEY(ID)
)

FLIGHT:-
ID INT NOT NULL AUTO_INCREMENT,
FLIGHT_NUMBER VARCHAR(20) NOT NULL,
OPERATING_AIRLINES VARCHAR(20) NOT NULL,
DEPARTURE_CITY VARCHAR(20) NOT NULL,
ARRIVAL_CITY       VARCHAR(20) NOT NULL,
DATE_OF_DEPARTURE DATE NOT NULL,
ESTIMATED_DEPARTURE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
PRIMARY KEY(ID)

////TIMESTAMP CONTAINS BOTH DATE AND TIME

USER:-
 
ID INT NOT NULL AUTO_INCREMENT ,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
EMAIL  VARCHAR(20),
PASSWORD VARCHAR(256),
PRIMARY KEY (ID),
UNIQUE KEY(EMAIL)

//in query : INSERT into flight VALUES(1,'AA1','American Airlines','AUS','NYC', STR_TO_DATE('02-03-2023', '%m-%d-%Y'),'2023-02-03 04:12:08') //IN database it will be stored as YY-MM-DD bcoz of String to date conversion
//while searching in form search by "MM-dd-yyyy" this format
